# Generated by Django 2.2.6 on 2019-10-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191021_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
